# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° de crédit')),
                ('date', models.DateField(verbose_name='Date de crédit')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire')),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant total')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant payé')),
                ('solde_restant', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Solde restant')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.client', verbose_name='Client')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Crédit Client',
                'verbose_name_plural': 'Crédits Clients',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='credits.creditclient', verbose_name='Crédit')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
    ]
