# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_charge', models.CharField(choices=[('fixe', 'Charge fixe'), ('variable', 'Charge variable')], max_length=20, verbose_name='Type de charge')),
            ],
            options={
                'verbose_name': 'Catégorie de Charge',
                'verbose_name_plural': 'Catégories de Charges',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant prévu')),
                ('frequence', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], max_length=20, verbose_name='Fréquence')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.categoriecharge', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Planification Charge',
                'verbose_name_plural': 'Planifications Charges',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° de charge')),
                ('date', models.DateField(verbose_name='Date de la charge')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('fournisseur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fournisseur/Prestataire')),
                ('facture_numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de facture')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('payee', models.BooleanField(default=True, verbose_name='Payée')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.categoriecharge', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('budget_prevu', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Budget prévu')),
                ('budget_realise', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Budget réalisé')),
                ('ecart', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Écart')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.categoriecharge', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Budget Annuel',
                'verbose_name_plural': 'Budgets Annuels',
                'ordering': ['-annee', 'categorie'],
                'unique_together': {('annee', 'categorie')},
            },
        ),
    ]
