# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° employé')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénoms')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire de base')),
                ('prime_performance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('motif_sortie', models.TextField(blank=True, null=True, verbose_name='Motif de sortie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('sans_solde', 'Congé sans solde'), ('exceptionnel', 'Congé exceptionnel')], max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nb_jours', models.IntegerField(editable=False, verbose_name='Nombre de jours')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_approbation', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PaieSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de base')),
                ('prime_performance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prime de performance')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures supplémentaires')),
                ('taux_heure_sup', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux heure supplémentaire')),
                ('autres_primes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres primes')),
                ('avances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avances')),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres retenues')),
                ('salaire_brut', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Salaire brut')),
                ('salaire_net', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Salaire net')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Paie Salaire',
                'verbose_name_plural': 'Paies Salaires',
                'ordering': ['-annee', '-mois', 'employe'],
                'unique_together': {('employe', 'annee', 'mois')},
            },
        ),
    ]
