# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du magasin')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° de vente')),
                ('date', models.DateField(verbose_name='Date de vente')),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité vendue')),
                ('type_vente', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Crédit')], max_length=10, verbose_name='Type de vente')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire')),
                ('total_vente', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total vente')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.client', verbose_name='Client')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('commission_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Commission (%)')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin principal')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
