# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('type_vehicule', models.CharField(help_text='Ex: Camion, Voiture, Moto, etc.', max_length=100, verbose_name='Type de véhicule')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('couleur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition")),
                ('prix_acquisition', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'acquisition")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField(verbose_name='Date de maintenance')),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision'), ('reparation', 'Réparation'), ('controle', 'Contrôle technique'), ('autre', 'Autre')], max_length=100, verbose_name='Type de maintenance')),
                ('description', models.TextField(verbose_name='Description')),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût')),
                ('garage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Garage/Prestataire')),
                ('prochaine_maintenance', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_motorise.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Maintenance Véhicule',
                'verbose_name_plural': 'Maintenances Véhicules',
                'ordering': ['-date_maintenance'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="N° d'enregistrement")),
                ('date', models.DateField(verbose_name='Date')),
                ('quantite_carburant_semaine', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité carburant/semaine (L)')),
                ('prix_par_litre', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix par litre')),
                ('montant_semaine', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant par semaine')),
                ('montant_mois', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant par mois')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_motorise.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Consommation Carburant',
                'verbose_name_plural': 'Consommations Carburant',
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
