# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unite_mesure', models.CharField(help_text='Ex: kg, litre, pièce, etc.', max_length=50, verbose_name='Unité de mesure')),
                ('prix_vente_conseille', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente conseillé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enregistrement', models.CharField(max_length=50, unique=True, verbose_name="N° d'enregistrement")),
                ('date', models.DateField(verbose_name='Date de livraison')),
                ('quantite_livree', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité livrée')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat unitaire")),
                ('montant_total_achat', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name="Montant total d'achat")),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit livré')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
