# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassementProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('quantite_totale_vendue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité totale vendue')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Chiffre d'affaires")),
                ('cout_total_achat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Coût total d'achat")),
                ('profit_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Profit total')),
                ('marge_moyenne', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge moyenne (%)')),
                ('rang_rentabilite', models.IntegerField(verbose_name='Rang rentabilité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Classement Produit',
                'verbose_name_plural': 'Classements Produits',
                'ordering': ['rang_rentabilite', '-profit_total'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="N° d'analyse")),
                ('date', models.DateField(verbose_name="Date d'analyse")),
                ('quantite_achetee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité achetée')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat unitaire")),
                ('montant_achat', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name="Montant d'achat")),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité vendue')),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente unitaire')),
                ('montant_vente', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant de vente')),
                ('profit_brut', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Profit brut')),
                ('charges_associees', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Charges associées')),
                ('profit_net', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Profit net')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.commercial', verbose_name='Commercial')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Analyse de Profit',
                'verbose_name_plural': 'Analyses de Profits',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportProfitMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total achats')),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total ventes')),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total charges')),
                ('profit_brut', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit brut')),
                ('profit_net', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit net')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Rapport Profit Mensuel',
                'verbose_name_plural': 'Rapports Profits Mensuels',
                'ordering': ['-annee', '-mois', 'magasin'],
                'unique_together': {('annee', 'mois', 'magasin')},
            },
        ),
    ]
