# Generated by Django 4.2.23 on 2025-08-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant_entree', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_sortie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
