# Generated by Django 4.2.23 on 2025-08-15 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="N° d'inventaire")),
                ('date', models.DateField(verbose_name="Date d'inventaire")),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable inventaire')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('valide', 'Validé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° de mouvement')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('stock_initial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock initial')),
                ('stock_vendu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock vendu')),
                ('stock_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Stock final')),
                ('montant_ventes', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant des ventes')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.commercial', verbose_name='Commercial')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockActuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité actuelle')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name="Seuil d'alerte")),
                ('prix_moyen_achat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix moyen d'achat")),
                ('valeur_stock', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Valeur du stock')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock Actuel',
                'verbose_name_plural': 'Stocks Actuels',
                'ordering': ['magasin', 'produit'],
                'unique_together': {('magasin', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock théorique')),
                ('stock_physique', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock physique')),
                ('ecart', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Écart')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.inventaire', verbose_name='Inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne d'Inventaire",
                'verbose_name_plural': "Lignes d'Inventaire",
                'unique_together': {('inventaire', 'produit')},
            },
        ),
    ]
